#! /usr/bin/env python

import sys
import os
import gdown
import tarfile
from pathlib import Path

codes = {
        'sbi': 8801,
        'nic': 10301,
        }
if len(sys.argv) != 2:
    print('Usage: ./server <bank_name> (sbi, nic) ')
    exit(0)

else:
    bank = sys.argv[1]

    if bank in codes:
        if not os.path.isdir('ocr/weights/'):
            print('Downloading models')
            if not os.path.isfile('weights.tar.gz'):
                gdown.download('https://drive.google.com/uc?id=1BXggoCXKzCivAPAqs8DWDmnXTBtVZupK')
            outputdir = Path('ocr/')
            outputdir.mkdir(exist_ok=True, parents=True)
            signatures = Path('ocr/signatures').mkdir(exist_ok=True, parents=True)
            with tarfile.open('weights.tar.gz', 'r:gz') as tar:
                print('Extracting weights.tar.gz...')
                tar.extractall(path=outputdir)
                print('Done!')
                Path('weights.tar.gz').unlink(missing_ok=True)

        os.system(f'BANK_PORT={codes[bank]} python manage.py runserver 0.0.0.0:{codes[bank]}')


