# Generated by Django 6.0.2 on 2026-02-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_bankaccount_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='nep_name',
            field=models.CharField(null=True, blank=True, max_length=20),
            preserve_default=False,
        ),
    ]
