# Generated by Django 6.0.2 on 2026-02-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_bankaccount_nep_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='nep_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
