# Generated by Django 6.0.2 on 2026-02-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0004_alter_bankaccount_nep_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='nep_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
