# Generated by Django 6.0.2 on 2026-02-14 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0005_alter_bankaccount_nep_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='nep_name',
        ),
    ]
