# Generated by Django 6.0.2 on 2026-02-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0007_bankaccount_nep_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='bank_code',
            field=models.IntegerField(default=801),
        ),
    ]
